[package]
name = "serde_rton"
version = "0.3.1"
edition = "2024"
authors = ["ed1th"]
categories = ["encoding", "parser-implementations"]
readme = "README.md"
license = "GPL-3.0-or-later"
repository = "https://github.com/LambdaEd1th/serde_rton"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
byteorder = "1.5"
regex = "1.12"
num_enum = "0.7"
integer-encoding = "4.1"
simple-rijndael = "0.3"
md-5 = "0.11"
hex = "0.4"

[dev-dependencies]
serde_json = "1.0"
serde_yaml = "0.9"
